development:
  adapter: postgresql
  database: db/my_database
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: db/my_database
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/my_database
  pool: 5
  timeout: 5000